title:          SSH Tunnels with HiediSQL and Plink
type:           article
date_published: 2010-11-05
date_updated:   2012-01-02
image:          tunnel.jpg
summary:        "This post describes how to use Plink and HeidiSQL together to connect to MySQL servers via SSH tunnels, which can be tricky."
category:       Web Development
tags: 
    - HeidiSQL
    - SSH
    - SSH Tunnel
    - MySQL