title:          Teaching PHP: Course Curriculum
type:           article
date_published: 2009-08-03
date_updated:   2012-01-13
image:          php-sauce.jpg
summary:        "The problem, succinctly stated, is: How do you best organize 14 weeks of study to teach PHP to a group of motivated College students?"
category:       Web Development
tags: 
    - PHP
    - Instruction
    - Curriculum
    - Teaching
