title:       bioteà
url:         http://biotea.idiginfo.org
circa:       current
summary:     An RDF dataset and API for Pubmed Central Documents
mainscreenshot:
    file:    screenshot_main.png
    summary: Biotea Homepage

# screenshots:
#     - file:    ss_2.png
#       summary: Data Collection

#     - file:    ss_3.png
#       summary: Data Collection

#     - file:    ss_4.png
#       summary: Data Collection

#     - file:    ss_5.png
#       summary: Data Collection