title:          Playing with Asynchronous PHP Processing
type:           article
date_published: 2012-09-24
image:          flowchart.jpg
summary:        "In this post, I present a concept for creating a worker-process for asynchronous job queue processing in PHP using CRON"
category:       Web Development
tags:
    - PHP
    - PHP-CLI
    - Queuing
    - Web Development
    - Maintenance Script
    - Linux
    - Asynchronous