title:       Teaching - FSU LIS4368
url:         http://lis4368.cci.fsu.edu
circa:       current
summary:     I teach LIS4368 - Advanced Web Development as a senior-level course at FSU
mainscreenshot:
    file:    ss_1.png
    summary: Data Collection

screenshots:
    - file:    ss_2.png
      summary: Data Collection

    - file:    ss_3.png
      summary: Data Collection

    - file:    ss_4.png
      summary: Data Collection

    - file:    ss_5.png
      summary: Data Collection