title:       Teaching - FSU LIS4368
circa:       current
description: I teach LIS4368 - Advanced Web Development as a senior-level course at FSU
screenshots:
    - ss_1.png: Front Page,
    - ss_2.png: Data Collection,
    - ss_3.png: Tailored Messaging Page