title:       RU@Risk
circa:       current
summary:     A tailored messaging system and online data collection platform
mainscreenshot:
    file:    ss_1.png
    summary: Data Collection

screenshots:
    - file:    ss_2.png
      summary: Data Collection

    - file:    ss_3.png
      summary: Data Collection

    - file:    ss_4.png
      summary: Data Collection

    - file:    ss_5.png
      summary: Data Collection