title:       RU@Risk
circa:       current
description: A tailored messaging system and online data collection platform
screenshots:
    - ss_1.png: Front Page,
    - ss_2.png: Data Collection,
    - ss_3.png: Tailored Messaging Page